### ISSUE TITLE
MultiMap.prototype.size counts number of values, not keys

### ISSUE THREAD

**Issue by michaelficarra** [villadora/multi-map#2]
I would expect to receive the number of keys. If you disagree, can we add an `entriesSize` member?

**Comment by springuper** [comment]
+1

**Comment by mrstux** [comment]
I would expect to be able to iterate over the keys and or entries, and thus have the sizes for both

**Comment by KoryNunn** [comment]
The method for this in C++ is `count`: https://www.geeksforgeeks.org/multimapcount-in-c-stl/

This should be trivial to add.

**Comment by michaelficarra** [comment]
@KoryNunn Great, does that mean you're preparing a PR?

**Comment by KoryNunn** [comment]
Added and published as 1.1.0
